name: 'Post Deployment Success'

on: deployment_status

jobs:
  sitemap:
    name: ping bing and google with updates
    if: github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'production'
    runs-on: ubuntu-latest

    steps:
      - name: Ping Google
        run: |
          curl https://www.google.com/ping?sitemap=https://that.us/sitemap.xml
      - name: Ping Bing
        run: |
          curl https://www.bing.com/ping?sitemap=https://that.us/sitemap.xml
      - name: Purge CloudFlare
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_THATUS_ID }}/purge_cache" -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_PURGE_TOKEN }}" -H "Content-Type:application/json" --data '{"purge_everything":true}'
